### PR TITLE
Using Data Transfer Objects in Update Provider SmartContract Calls

### LINKED ISSUE #2544: Update provider, use map as input rather than object
Update provider smart contract endpoints currently use an object as input. This can cause an issue distinguishing between unchanged and default settings. 

A suggestion; we change the input to the update_provider endpoints to take a map of updated fields as input rather than an object. 

Will need `zbox` ad `zwallet` changes as well.

### PR DESCRIPTION
**Pull request by sunilmhta**
## Fixes
#2544 
## Tests
Tasks to complete before merging PR:
- [x]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk: https://github.com/0chain/gosdk/pull/1085 
- system_test:
- zboxcli:
- zwalletcli: https://github.com/0chain/zwalletcli/pull/274
- Other: ...

### CODE REVIEW

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | sprint-july-1  |
| authorizer  | sprint-july-1  |
| 0box  | sprint-july-1  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | staging  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | staging  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | sprint-july-1  |
| zboxcli  | fix/fileMetaHash  |
| zwalletcli  | sprint-july-1  |
| 0chain  | sprint-july-1  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Pull request merged**
