### PR TITLE
Remove min lock and interestpoolsc settings

### LINKED ISSUE #2179: Remove references to stake_pool_pay_interests. also remove min_lock.
To avoid confusion we should remove references to the non existant endpoint stake_pool_pay_interests .

In particular in [sc.yaml](https://github.com/0chain/0chain/blob/4ceada42b5b173e1a468fc9becb88ca6bea74441/docker.local/config/sc.yaml#L251) and [sc.go](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/sc.go#L118) and anywhere else.

Also remove reference to interestpoolsc from[ sc.yaml.](https://github.com/0chain/0chain/blob/4ceada42b5b173e1a468fc9becb88ca6bea74441/docker.local/config/sc.yaml#L15) and [minersc.interest_rate.](https://github.com/0chain/0chain/blob/4ceada42b5b173e1a468fc9becb88ca6bea74441/docker.local/config/sc.yaml#L65)

Also we should remove all reference to `min_lock` settings that are no longer used. This includes sc.yaml and in the code.

### PR DESCRIPTION
**Pull request by Sriep**
## Fixes
closes https://github.com/0chain/0chain/issues/2179
## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test: https://github.com/0chain/system_test/pull/608
- zboxcli:
- zwalletcli:
- Other: ...
Needs to be merged simultaneously with https://github.com/0chain/system_test/pull/608

### CODE REVIEW

**Review by peterlimg — APPROVED** [review]
LGTM

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | statkepool_min_lock  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | remove_min_lock  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  |   |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by peterlimg** [comment]
Could merge once https://github.com/0chain/0chain/actions/runs/4571883489 is green.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | statkepool_min_lock  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | remove_min_lock  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | statkepool_min_lock  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | remove_min_lock  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
