### PR TITLE
Benchmark fix storage sc tests

### PR DESCRIPTION
**Pull request by Sriep**
## Fixes
Fixes storagesc tests:
* storage.commit_connection              
* storage.add_blobber                   
* storage.cancel_allocation       
* storage.collect_reward                 
* storage.finalize_allocation            
* storage.free_allocation_request        
* storage.free_update_allocation         
* storage.stake_pool_unlock              
* storage.update_blobber_settings        
* storage.write_pool_unlock
## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | YES  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | benchmark_write_pool  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]

**Comment by peterlimg** [comment]
@Sriep please resolve the system tests, or @Kishan-Dhakan please check if there are flaky tests

**Comment by Sriep** [comment]
These are benchmark-only changes, so they should not affect system tests. I'll keep retesting until they pass.

**Pull request merged**
