### PR TITLE
Add Saved data field in Storage node and eventsdb blobber

### LINKED ISSUE #787: Event db API: data stored in network.
We need an endpoint to return the amount of data stored on the network.

# storagesc

Each blobber will send a [WriteMarker](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L1018) for each change to data stored on the blobber.

The [StorageNode](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L304) will have a new field to reflect the amount of data stored on the blobber. This field is updated with the information in the WriteMarker each call to [commitBlobberConnection](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L556).

Each time this blobber field is updated we need to emit an event to update the blobber table with this new value. 

# Event db

This will require a new SavedData field on the Blobber table.

The new endpoint will then return the aggregate value for all data stored across all blobbers.

```sql
SELECT SUM(saved_data) AS total FROM blobber;
```

### PR DESCRIPTION
**Pull request by amanjain97**
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR  
  
Associated PRs (Link as appropriate):
...

### CODE REVIEW

**Comment by amanjain97** [comment]
Related issue: https://github.com/0chain/0chain/issues/787

**Review by kushthedude — APPROVED** [review]
Looks good to me, lets do a sanity on local chain before we can get it in

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | add-saved-data  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by kushthedude — APPROVED** [review]
System tests looked like flake earlier

**Pull request merged**
