### PR TITLE
Fix chain stuck on large network issue

### PR DESCRIPTION
**Pull request by peterlimg**
# Changes:
- Changed API endpoint from `/v1/_x2m/block/state_change/get` to `/v1/_x2x/block/state_change/get`, so we now can get `state changes` from both miners and sharders.
- Lots of changes on improving chain stabilization

# Fixes:
- #672
- #635
- #623 
- #634 
- #654 
- #626 
- #613
- #614
- #600
- #611
- #612
- #622

### CODE REVIEW

**Comment by stewartie4** [comment]
@peterlimg System tests look mostly good for this branch, except for a single failure due to a bad request 
image
https://github.com/0chain/system_test/runs/4277966564?check_suite_focus=true
Are there API updates to /v1/block/ with these changes? if so we'll need to update the tests

**Comment by peterlimg** [comment]
@stewartie4 there should have no updates to /v1/block API endpoints, I'll have a check.

**Comment by stewartie4** [comment]
the above now looks resolved, is this ready to merge?

**Comment by peterlimg** [comment]
@stewartie4 do you mean the system_tests error is resolved? I think the changes on `common.Response()` may caused the system test errors. Anyway, I have changed it back, so if the system tests work fine, then we can merge this now.

**Comment by stewartie4** [comment]
Yes the issue with that API is gone thanks Peter

**Pull request merged**
