### PR TITLE
removed curator functionality

### LINKED ISSUE #2153: remove curator feature
there was a curator functionality before. look everything related to "curator" in 0chain, gosdk, system-test and cli tools repos and delete related code

### PR DESCRIPTION
**Pull request by Hitenjain14**
## Changes
Removed curator functionality from 0chain  #2153 . 

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk: https://github.com/0chain/gosdk/pull/819
- system_test: https://github.com/0chain/system_test/pull/578
- zboxcli: https://github.com/0chain/zboxcli/pull/372
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by Hitenjain14** [comment]
Will be updating related repos which are using `curator_transfer_allocation` to update the `allocation owner` .

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by dabasov** [comment]
remove files copletely

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | rm_curator  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | rm_curator  |
| zwalletcli  | staging  |
| 0chain  | rm-curator  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | rm_curator  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | rm_curator  |
| zwalletcli  | staging  |
| 0chain  | rm-curator  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
