### PR TITLE
not available

### LINKED ISSUE #2504: Toggle blobber availability to be used in new allocations.
Currently, we have an `is_avaliable` field, but it can't be set.

### PR DESCRIPTION
**Pull request by Sriep**
## Fixes
Change is_available to not_available and allow setting with update_blobber_settings.
## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:https://github.com/0chain/gosdk/pull/1043
- system_test: https://github.com/0chain/system_test/pull/702
- zboxcli:https://github.com/0chain/zboxcli/pull/457
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by peterlimg** [comment]
LGTM, please fix the system test error.

**Comment by Sriep** [comment]
This needs to be merged simultaneously with the system test PR https://github.com/0chain/system_test/pull/702

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by Kishan-Dhakan** [comment]
Started the manual run: https://github.com/0chain/0chain/actions/runs/5248330220/jobs/9479657684, if it passes it will unblock both PRs

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by peterlimg** [comment]
@Sriep see errors `unknown flag: --not_available` in system tests, please fix and we will merge once it pass

**Review by peterlimg — APPROVED** [review]

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | not_available  |
| zboxcli  | not_available  |
| zwalletcli  | staging  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | not_available  |
| zboxcli  | not_available  |
| zwalletcli  | staging  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_avaliable  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | not_available  |
| zboxcli  | not_available  |
| zwalletcli  | sprint-june-5  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | sprint-june-5  |
| zboxcli  | not_available  |
| zwalletcli  | sprint-june-5  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-june-5  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | sprint-june-5  |
| zwalletcli  | sprint-june-5  |
| 0chain  | sprint-june-5  |
| blobber  | fix/cache_allocation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | not_available  |
| gosdk  | not_available  |
| zboxcli  | not_available  |
| zwalletcli  | sprint-june-5  |
| 0chain  | not_avaliable  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Pull request merged**
