### PR TITLE
don't DPanic on unranked miners in RoundInfoHandler

### LINKED ISSUE #1038: Round info diagnostics page panic
Refresh page https://testnet1.devnet-0chain.net/miner02/_diagnostics/round_info several times, we will see panic as shown below:

goroutine 343060648 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa5
0chain.net/chaincore/chain.RoundInfoHandler.func1(0x154e280, 0xc002de1180)
	/0chain/go/0chain.net/chaincore/chain/handler.go:1254 +0x6e
panic(0x13259c0, 0xc0075baeb0)
	/usr/local/go/src/runtime/panic.go:971 +0x4c7
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0102d2780, 0x0, 0x0, 0x0)
	/0chain/go/0chain.net/vendor/go.uber.org/zap/zapcore/entry.go:234 +0x7b4
go.uber.org/zap.(*Logger).DPanic(0xc00046c5f0, 0xc00a68a880, 0x3e, 0x0, 0x0, 0x0)
	/0chain/go/0chain.net/vendor/go.uber.org/zap/logger.go:217 +0x7d
0chain.net/chaincore/round.(*Round).GetMinerRank(0xc002e82900, 0xc0006d7a00, 0x0)
	/0chain/go/0chain.net/chaincore/round/entity.go:560 +0x754
0chain.net/chaincore/chain.RoundInfoHandler.func3(0x1, 0x0, 0x0)
	/0chain/go/0chain.net/chaincore/chain/handler.go:1341 +0x148
sort.insertionSort_func(0xc00c8b7360, 0xc00ad58d80, 0x0, 0xf)
	/usr/local/go/src/sort/zfuncversion.go:12 +0x88
sort.stable_func(0xc00c8b7360, 0xc00ad58d80, 0xf)
	/usr/local/go/src/sort/zfuncversion.go:171 +0xc5
sort.SliceStable(0x130f080, 0xc015d82ed0, 0xc00c8b7360)
	/usr/local/go/src/sort/slice.go:32 +0xec
0chain.net/chaincore/chain.RoundInfoHandler(0x154e280, 0xc002de1180, 0xc008334700)
	/0chain/go/0chain.net/chaincore/chain/handler.go:1337 +0x1177
0chain.net/core/common.Recover.func1(0x154e280, 0xc002de1180, 0xc008334700)
	/0chain/go/0chain.net/core/common/mdw_recover.go:42 +0xbb
net/http.HandlerFunc.ServeHTTP(0xc0005126f0, 0x154e280, 0xc002de1180, 0xc008334700)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/didip/tollbooth.LimitHandler.func1(0x154e280, 0xc002de1180, 0xc008334700)
	/0chain/go/0chain.net/vendor/github.com/didip/tollbooth/tollbooth.go:171 +0x244
net/http.HandlerFunc.ServeHTTP(0xc00ad58ce0, 0x154e280, 0xc002de1180, 0xc008334700)
	/usr/local/go/src/net/http/server.go:2069 +0x44
0chain.net/core/common.UserRateLimit.func1(0x154e280, 0xc002de1180, 0xc008334700)
	/0chain/go/0chain.net/core/common/rate_limter.go:50 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc0014935c0, 0x154e280, 0xc002de1180, 0xc008334700)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0x1a41160, 0x154e280, 0xc002de1180, 0xc008334700)
	/usr/local/go/src/net/http/server.go:2448 +0x1ab
net/http.serverHandler.ServeHTTP(0xc000240460, 0x154e280, 0xc002de1180, 0xc008334700)
	/usr/local/go/src/net/http/server.go:2887 +0x22b
net/http.(*conn).serve(0xc0037a3d60, 0x15500b0, 0xc00f2c2200)
	/usr/local/go/src/net/http/server.go:1952 +0x1c25
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x96e

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
## Changes
No longer DPanic when querying round info in VRF phase.

## Fixes
Close #1038 

## Tests 
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by peterlimg — DISMISSED** [review]
lgtm

**Comment by rrrooommmaaa** [comment]
Looks like the newly added test affects or is affected by other miner tests, as it is completes ok when run separately.
There is a quite complex setup, any idea where to look for?
@peterlimg @dabasov @Sriep ?

**Review by dabasov — DISMISSED** [review]
lgtm

**Comment by peterlimg** [comment]
@rrrooommmaaa please fix the unit test as the way we talked

**Comment by rrrooommmaaa** [comment]
> @rrrooommmaaa please fix the unit test as the way we talked

I isolated Chain and miner.Chain objects but it looks like there are conflicts on `memorystore` level. Would it help to set different ChainIDs or should we run separate instances of redis?

**Comment by peterlimg** [comment]
@rrrooommmaaa the reason for defining the `Chainer` interface is that we can mock it in unit tests, I find the unit test are still using `GetMinerChain()`, this is a global variable, which we should avoid using in unit tests, it is also the reason why the tests were failing. Please run mockery to generate mock files and then mock the interface in unit tests, check [here](https://github.com/0chain/0chain/blob/4a77203202230838a0e7aabd98e6da11eee134d8/code/go/0chain.net/sharder/m_handler_test.go#L53-L65) to see how the mock works.

Also, please keep the changes small, I see the signature changes of `SetupMinerChain`, which is unnecessary(if refactor needed, we can do it in new PRs), we should only change the function where the `RoundInfoHandler()` is called, which is `handlersMap`, and seems it already has the `Chainer` interface.

Another thing to note is do the handler in similar way we do for others, we'd better code in the same style when possible, so please do it in following way:

```go
func RoundInfoHandler(c Chainer) ReqRespHandlerf {
 return func(w http.ResponseWriter, r *http.Request) {
    ...
  } 
}
```

**Comment by rrrooommmaaa** [comment]
> I find the unit test are still using `GetMinerChain()`,

please translate to English
which test? or tests?

> the reason for defining the Chainer interface is that we can mock it in unit tests

My purpose was not to mock the chain, but possibility to actually create a chain without conflicts with other tests

**Comment by rrrooommmaaa** [comment]
ok, I created PR #1123 based on mock tests, but I suggest to find a way to move forward with these refactorings to make it possible to actually run several chains

**Comment by peterlimg** [comment]
> ok, I created PR #1123 based on mock tests, but I suggest to find a way to move forward with these refactorings to make it possible to actually run several chains

Basically all those `handlers` that use the global chain by calling `GetMinerChain()` or `GetSharderMiner()` needs to be refactored in similar way we do in this PR. But the priority is low, so don't focus on this unless errors happen.

**Comment by peterlimg** [comment]
Fixed on #1123

**Pull request closed without merging**
