### PR TITLE
Add new `/v1/healthcheck` API to sharder

### LINKED ISSUE #1437: Add new `/health` API to check if the current node is available
Return basic info, like the `uptime`, `build commit id`, `version`. 

We need this API because currently, the gosdk is calling `/_health_check` endpoint to see if a sharder is available. However that endpoint is an webpage handler that provide diagnostic info for sharders, and it will update the metrics stats each time the endpoint is called, which is a slow and will cause goroutine leaks and slow down the sharders. So we will need this new light `/health` API endpoint to resolve the goroutine issue. We  should also not expose all the diagnostic pages to public when go to production.

We will also need to check other APIs that return html responses and used by gosdk.

### PR DESCRIPTION
**Pull request by peterlimg**
## Fixes

- #1437 

## Changes

- Added a new `/v1/healthcheck` endpoint that returns basic sharder info, `uptime`, `build tag`, `latest finalized block summary`, etc. 
- Added API logger to log the received api requests and response status and process time.

- Changed the `/_health_check` to `/_healthcheck` to force gosdk users to upgrade sdk so that the new endpoint will be used. 

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber: https://github.com/0chain/blobber/pull/737
- gosdk: https://github.com/0chain/gosdk/pull/503
- system_test:
- zboxcli: https://github.com/0chain/zboxcli/pull/271
- zwalletcli: https://github.com/0chain/zwalletcli/pull/151
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/healthcheck  |
| zwalletcli  | fix/healthcheck  |
| 0chain  | feature/api-healthcheck  |
| blobber  | fix/healthcheck  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/healthcheck  |
| zboxcli  | fix/healthcheck  |
| zwalletcli  | fix/healthcheck  |
| 0chain  | feature/api-healthcheck  |
| blobber  | fix/healthcheck  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/healthcheck  |
| zboxcli  | fix/healthcheck  |
| zwalletcli  | fix/healthcheck  |
| 0chain  | feature/api-healthcheck  |
| blobber  | fix/healthcheck  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by peterlimg** [comment]
[917c90c](https://github.com/0chain/0chain/pull/1445/commits/917c90c25f35f7e009227420595e843ab096d3e1) this commit does not work, I'll send a PR to revert it.

**Pull request merged**
