### PR TITLE
fixed msg pack in git actions

### PR DESCRIPTION
**Pull request by Manali-Jain-squareops**
## Fixes
https://github.com/0chain/0chain/issues/1687

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by boddumanohar — APPROVED** [review]
LGTM

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix_unit_test  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by peterlimg** [comment]
Seems this PR is causing the staging unit test failure, we will need to revert or fire new PR to fix. @Manali-Jain-squareops @dabasov

**Comment by dabasov** [comment]
@peterlimg how is it possible, all checks were green for this PR

**Comment by fabioDMFerreira** [comment]
@dabasov adding
```
          git init
          git remote add 0chain https://github.com/0chain/0chain.git
```
may have fixed some inconsistency problem in the environment. The unit test job is failing due to this change though.

https://github.com/0chain/0chain/actions/runs/3151606734/jobs/5125771021

cc @Manali-Jain-squareops

**Comment by Manali-Jain-squareops** [comment]
@fabioDMFerreira  https://github.com/0chain/0chain/pull/1717 check this i have added condition

**Pull request merged**
