### PR TITLE
install mockery on conductor-standard-tests

### PR DESCRIPTION
**Pull request by fabioDMFerreira**

### CODE REVIEW

**Review by peterlimg — APPROVED** [review]
lgtm

**Review by peterlimg — CHANGES_REQUESTED** [review]
hmm, we will need to setup go in the action to build the mocks.

```
    - name: Setup go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
```

**Review by peterlimg — DISMISSED** [review]
Please rebase to clean up the `.` commits

**Comment by fabioDMFerreira** [comment]
@m-s-a-c Any clue why the following workflow is failing?

https://github.com/0chain/0chain/actions/runs/3151398298/jobs/5125297191

It is also failing in other branches
https://github.com/0chain/0chain/actions/runs/3150563608/jobs/5123492968

**Comment by peterlimg** [comment]
@fabioDMFerreira it's a problem introduced by PR #1703, see comments there.

**Comment by peterlimg** [comment]
@fabioDMFerreira please merge the msgp fix from staging and re-run the tests

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
