### PR TITLE
Move Min lock demand from blobber to smart contract setting

### LINKED ISSUE #2457: Set min_lock_demand in 0chain
The min_lock_demand is a global item and set to 100% 
also delete it from blobber completely

### PR DESCRIPTION
**Pull request by Sriep**
## Fixes
Adds new `conf.MinLockDemand = 0.1` setting to sc.yaml
## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk: https://github.com/0chain/gosdk/pull/1046
- system_test: https://github.com/0chain/system_test/pull/724
- zboxcli: https://github.com/0chain/zboxcli/pull/458
- zwalletcli: https://github.com/0chain/zwalletcli/pull/267
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | min_lock_demand  |
| gosdk  | min_lock_demand  |
| zboxcli  | min_lock_demand  |
| zwalletcli  | staging  |
| 0chain  | min_lock_demand  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | min_lock_demand  |
| gosdk  | min_lock_demand  |
| zboxcli  | min_lock_demand  |
| zwalletcli  | min_lock_demand  |
| 0chain  | min_lock_demand  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | min_lock_demand  |
| gosdk  | min_lock_demand  |
| zboxcli  | min_lock_demand  |
| zwalletcli  | min_lock_demand  |
| 0chain  | min_lock_demand  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | min_lock_demand  |
| gosdk  | staging  |
| zboxcli  | min_lock_demand  |
| zwalletcli  | min_lock_demand  |
| 0chain  | min_lock_demand  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Pull request merged**
