### PR TITLE
﻿ISSUE#195 github.com/spf13/viper is not thread safe

### PR DESCRIPTION
**Pull request by platsko**
There is a suggestion to solve the problem with the Viper package using wrapper functions. Let's discuss this.

### CODE REVIEW

**Review by Sriep — CHANGES_REQUESTED** [review]
Looks promising. We need unit tests for `core/viper`. What about reading in various 0chain config files, writing them out then rereading them?

**Comment by platsko** [comment]
@Sriep
During testing, significant shortcomings in the implementation were revealed, many methods cannot be thread-safe - I think it would be better to get rid of them altogether. Please see the last commit.

**Comment by Sriep** [comment]
Do we use any of the non-thread-safe methods? 

Eye on the goal: We don't want race errors. So either avoid using unsafe viper methods or make sure they are only accessed from one thread.

**Comment by Sriep** [comment]
I think we just have to let the non-thread-safe methods stand. Assume they are always called safely.

If necessary we can then raise a separate issue to check our usage of non-thread-safe viper methods and, if necessary, fix that in a separate PR.

**Review by Sriep — APPROVED** [review]

**Pull request merged**
