### PR TITLE
remove interest from miner/sharder

### LINKED ISSUE #946: Remove interest from miners and sharders
We are reward miners with to block rewards, not interest.

Remove the interest rate from miners and sharders. 

Remove [inerestst rate](https://github.com/0chain/0chain/blob/staging/docker.local/config/sc.yaml#L39) and interest decline rate from sc.yaml and settings. 
Remove code that uses the values to calculate amount.
Remove code that returns interest related data.

This is a split of https://github.com/0chain/0chain/issues/533

### PR DESCRIPTION
**Pull request by ssardana96**
- minersc.interest_rate and minersc.interest_decline_rate removed

Tasks to complete before merging PR:
- [x]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [x]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [x]  Merge your system tests PR to master BEFORE merging this PR  
  
Associated PRs (Link as appropriate):
...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | miner_sharder_interest  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | miner_sharder_interest  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Sriep — APPROVED** [review]
Looks ok once https://github.com/0chain/system_test/pull/170 has been merged and test rerun.

**Review by kushthedude — COMMENTED** [review]
@ssardana08 Can we delete the system_tests related to interests & then merge this PR?

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | miner_sharder_interest  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
