### PR TITLE
Add script to configure network for ubuntu wsl hosts

### LINKED ISSUE #1817: Add script to configure network for Ubuntu & WSL hosts
Following `macos_network.sh` and `windows_network.ps1`, we need to add a script to configure network for Ubuntu hosts as well as Windows hosts that run the cluster inside WSL2 that uses docker. Also we need to mention this in the README as well as the documentation. Without configuring the network, `zwallet` and `zbox` commands that are run locally cannot resolve addresses in the docker network sddress `198.18.0.0/15`.

### PR DESCRIPTION
**Pull request by devyetii**
## Fixes
- `zbox` and `zwallet` commands cannot resolve addresses when run on Ubuntu/WSL hosts that use docker to host run the network.

## Changes
- Added script to configure network in Ubuntu/WSL.
- Refered to it in README
## Need to be mentioned in CHANGELOG.md?
No idea.

## Tests
Tasks to complete before merging PR:
- [x]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [x]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by devyetii** [comment]
@peterlimg Tests passed. Kindly review.

**Comment by devyetii** [comment]
Will be moved to another issue

**Review by dabasov — COMMENTED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | YES  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 1817-add-script-to-configure-network-for-ubuntu-wsl-hosts  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
