### PR TITLE
Add delete authorizer payload with ID

### LINKED ISSUE #1625: [Authorizer] Bugfix
- Delete
there is already delete txn type ``delete-authorizer`` need to add to the zwalletcli and add check that only sc owner can execute it.
authorizer when deleted from events_db isn't deleted, but soft deleted but is deleted from MPT, so it can't be added again. also pool is not deleted from MPT.
- Update
for update allow to update the URL of the authorizer, everybody with a delegate wallet can update the authorizer  (allowed for the operational wallet)
- Authorizer startup
on authorizer, startup run update if needed
- Healthcheck
part of #1044

### PR DESCRIPTION
**Pull request by uneet7**
## Fixes
#1625 

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by dabasov — APPROVED** [review]
lgtm

**Review by peterlimg — CHANGES_REQUESTED** [review]
Seems using the different msgp, please run `make install-msgp` and re-run msgp to see if there are changes. Anyway, the msgp checking script in github actions seems not working.

**Comment by uneet7** [comment]
> Seems using the different msgp, please run `make install-msgp` and re-run msgp to see if there are changes. Anyway, the msgp checking script in github actions seems not working.

@peterlimg , I uninstalled msgp package installed from $GOPATH/src and $GOBIN and ran the following commands
```
make install-msgp
make msgp
```
The output is still same

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 1625-delete-authorizer-bugfix  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by peterlimg** [comment]
@uneet7 you will need to run system tests manually with zwalletcli and zboxcli on related branch to pass the tests, otherwise they would just used the staging code by default.

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | fix_unit_test  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
