### PR TITLE
add file_options_changed

### PR DESCRIPTION
**Pull request by devyetii**
## Fixes
- Some sdk clients don't yet support allocation file options, so till it's added I'll add an indication to mention if the client actually changed file options or not. 
## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk: 0chain/gosdk#762
- system_test: 0chain/system_test#541
- zboxcli: 0chain/zboxcli#353
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/allocation-file-options-not-supported-by-some-clients  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/file-options-not-supported-by-some-sdk-clients  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by peterlimg** [comment]
@devyetii please check system tests errors

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/allocation-file-options-not-supported-by-some-clients  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/file-options-not-supported-by-some-sdk-clients  |
| zwalletcli  | staging  |
| 0chain  | fix/file-options-not-supported-by-some-sdk-clients  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
