### PR TITLE
Get sharders from the MPT

### PR DESCRIPTION
**Pull request by boddumanohar**
## Fixes
https://github.com/0chain/0chain/issues/1674

## Changes
get sharders from MPT node

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 1674  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 1674  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by boddumanohar** [comment]
miner deployment is failing with this error. Taking a look. 

```
panic: runtime error: integer divide by zero
Fri, Sep 30 2022 2:47:07 pm	
Fri, Sep 30 2022 2:47:07 pm	goroutine 280 [running]:
Fri, Sep 30 2022 2:47:07 pm	0chain.net/chaincore/currency.DistributeCoin(0x0, 0x0)
Fri, Sep 30 2022 2:47:07 pm	/0chain/code/go/0chain.net/chaincore/currency/currency.go:173 +0x105
Fri, Sep 30 2022 2:47:07 pm	0chain.net/smartcontract/minersc.(*MinerSmartContract).payShardersAndDelegates(0xc000524000, 0x0, 0x1908b100, 0xc000000b40, 0xc0008a3a00, {0x189b3a0, 0xc0004f2840})
Fri, Sep 30 2022 2:47:07 pm	/0chain/code/go/0chain.net/smartcontract/minersc/fees.go:485 +0x1a9
Fri, Sep 30 2022 2:47:07 pm	0chain.net/smartcontract/minersc.(*MinerSmartContract).payFees(0xc000524000, 0xc000a6f000, {0x42a819, 0x1eb4b98, 0xc00007fab8}, 0xc0008a3a00, {0x189b3a0, 0xc0004f2840})
Fri, Sep 30 2022 2:47:07 pm	/0chain/code/go/0chain.net/smartcontract/minersc/fees.go:379 +0x13de
Fri, Sep 30 2022 2:47:07 pm	0chain.net/smartcontract/minersc.(*MinerSmartContract).Execute(0xc000524000, 0xc000a6f000, {0xc000cfbf00, 0x7}, {0xc000164ab0, 0x11, 0x18}, {0x189b3a0, 0xc0004f2840})
Fri, Sep 30 2022 2:47:07 pm	/0chain/code/go/0chain.net/smartcontract/minersc/sc.go:132 +0x3c9
Fri, Sep 30 2022 2:47:07 pm	0chain.net/chaincore/smartcontract.ExecuteWithStats({0x18969a8, 0xc000524000}, 0xc000798f00, {0xc000cfbf00, 0x7}, {0xc000164ab0, 0x11, 0x18}, {0x189b3a0, 0xc0004f2840})
Fri, Sep 30 2022 2:47:07 pm	/0chain/code/go/0chain.net/chaincore/smartcontract/handler.go:51 +0x112
Fri, Sep 30 2022 2:47:07 pm	0chain.net/chaincore/smartcontract.ExecuteSmartContract(0xc000798f00, 0xc0007cb500, {0x189b3a0, 0xc0004f2840})
Fri, Sep 30 2022 2:47:07 pm	/0chain/code/go/0chain.net/chaincore/smartcontract/handler.go:66 +0x13d
Fri, Sep 30 2022 2:47:07 pm	0chain.net/chaincore/chain.(*Chain).ExecuteSmartContract.func1()
Fri, Sep 30 2022 2:47:07 pm	/0chain/code/go/0chain.net/chaincore/chain/state.go:132 +0x7c
Fri, Sep 30 2022 2:47:07 pm	created by 0chain.net/chaincore/chain.(*Chain).ExecuteSmartContract
Fri, Sep 30 2022 2:47:07 pm	/0chain/code/go/0chain.net/chaincore/chain/state.go:131 +0x2b3
```

**Comment by peterlimg** [comment]
@boddumanohar good catch and fix. Seems blobber staking are failing on system tests, perhaps the sharders are not getting registered. I'll have a check.

**Comment by boddumanohar** [comment]
@peterlimg  what could we do to get the sharders registered in MPT before someone calls `GetBlockSharders`?

**Comment by peterlimg** [comment]
@boddumanohar basically we can't avoid user to call `GetBlockSharders` before sharders are registered as it takes time for sharders to register themself to the network. What we can do perhaps is adjust the logic to wait for sharders to be registered before taking actions. Or we will need to return errors. But this should only happens when network is just started, it should be fine afterwords.

**Comment by peterlimg** [comment]
@boddumanohar I see the problem, it is the chain that stuck caused the system test fail. I've been doing some minor fix and experience on branch [fix/get-sharder-from-mpt](https://github.com/0chain/0chain/tree/fix/get-sharders-from-mpt) on top this branch. I'll merge it into this after the stuck is fixed.

**Pull request merged**
