### PR TITLE
unit tests fot health check

### PR DESCRIPTION
**Pull request by jkrus**
## Tests 
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by ma2b0043** [comment]
@jkrus @moldis when can we expect to close this PR?

**Review by moldis — APPROVED** [review]
Looks good

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by peterlimg** [comment]
@jkrus please update system_tests errors.

**Pull request merged**
