### PR TITLE
parse zcn config

### LINKED ISSUE #2417: No conversion form tokens when reading zcn settings from config file
Zcn currency settings read from the config file are using different units to that used elsewhere.

In zcn min_stake is read in [config.go](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/zcnsc/config.go#L133)
```
conf.MinStakeAmount = currency.Coin(cfg.GetInt64(postfix(MinStakeAmount)))
```
Note no conversion from ZCN. 

In storages min_stake is read in [config.go](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/config.go#L335)
```
conf.MinStake, err = currency.ParseZCN(scc.GetFloat64(pfx + "min_stake"))
```
Notice the [currency.ParseZCN](https://github.com/0chain/common/blob/main/core/currency/currency.go#L57) function that multiplies by 1e10

When we update the settings in [UpdateConfig](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/zcnsc/nodes.go#L91) we do the conversion correctly
```
gn.MinStakeAmount, err = currency.ParseZCN(amount)
```

### PR DESCRIPTION
**Pull request by Sriep**
## Fixes
Converts zcn config currency amounts by multiplying by 100000000. So zcn works the same way as other smart contracts.
## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by dabasov — APPROVED** [review]
lgtm

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | zcn_parse_zcn  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by peterlimg — APPROVED** [review]
LGTM

**Pull request merged**
