### PR TITLE
Test lp sharder disk utilization cold tier

### PR DESCRIPTION
**Pull request by platsko**

### CODE REVIEW

**Review by moldis — APPROVED** [review]
Looks good, just need to fix lint

**Review by moldis — CHANGES_REQUESTED** [review]
Fix lint pipeline

**Review by peterlimg — CHANGES_REQUESTED** [review]
Please rename codeTier.go to code_tier.go, so as the codeTier_test.go, thanks.

**Comment by peterlimg** [comment]
Replaced by #1345

**Pull request closed without merging**
