### PR TITLE
Hotfix to remove DbAccess settings from MPT

### PR DESCRIPTION
**Pull request by Sriep**
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR  
  
Associated PRs (Link as appropriate):
...

### CODE REVIEW

**Review by kushthedude — COMMENTED** [review]
Does this mean we will get the DB access creds from the sc.yaml config file passed during deployment itself?

**Comment by Sriep** [comment]
This should prevent saving and loading EventDb logging details from MPT. You also cannot change anymore from an `update_global_settings` transaction only by editing the `0chain.yaml` and restarting the miner. The logging details are therefore defined on a sharder by sharder case rather than forced to the same for the whole chain.

**Review by kushthedude — APPROVED** [review]
Looks good to me 👍🏽

**Review by peterlimg — APPROVED** [review]
LGTM

**Pull request merged**
