### PR TITLE
Resovle @peterlimg's comment on #1802 -  Use ! instead of == false

### LINKED ISSUE #1769: Miners/Sharders nodes could be added without limitation
We don't have any limit for adding miners or sharders to the the nodes list, malicious users could attack the network by adding lots of faked nodes to the list.

### PR DESCRIPTION
**Pull request by devyetii**
## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by devyetii** [comment]
@peterlimg  Here I resolve your comment on #1802 which is to use "!" instead of "== false". I opened a new branch with PR as the previous one was merged before you added your comment. The change is minor so I think it's fine to stop the system tests, also cmiiw. Kindly review and merge if it looks good to you. cc @dabasov

**Comment by peterlimg** [comment]
@devyetii please also fix this in `AddSharder` SC

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 1769-minerssharders-nodes-could-be-added-without-limitation-1  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
