### PR TITLE
Feature/notify pr

### PR DESCRIPTION
**Pull request by stewartie4**
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR  
  
Associated PRs (Link as appropriate):
blobber: https://github.com/0chain/blobber/pull/478
zwalletcli: https://github.com/0chain/zwalletcli/pull/80
zboxxli: https://github.com/0chain/zboxcli/pull/150
gosdk: https://github.com/0chain/gosdk/pull/348
actions: https://github.com/0chain/actions/pull/8

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [pending] with the following config
| repo  | value |
| ------------- | ------------- |
| system-tests  | master  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| miner  |   |
| sharder  |   |
| blobber  | staging  |
| validator  |   |
| zbox  |   |
| zblock  |   |
| zdns  |   |
| explorer  |   |
| zproxy  |   |
| zsearch  |   |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| repo  | value |
| ------------- | ------------- |
| system-tests  | master  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| miner  |   |
| sharder  |   |
| blobber  | staging  |
| validator  |   |
| zbox  |   |
| zblock  |   |
| zdns  |   |
| explorer  |   |
| zproxy  |   |
| zsearch  |   |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| repo  | value |
| ------------- | ------------- |
| system-tests  | feature/test-branch  |
| zboxcli  | feature/notify-pr-zboxcli  |
| zwalletcli  | feature/notify-pr-zwalletcli  |
| 0chain  | feature/notify-pr  |
| blobber  | feature/notify-pr-blobber  |
| go-sdk  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| repo  | value |
| ------------- | ------------- |
| system-tests  | feature/test-branch  |
| zboxcli  | feature/notify-pr-zboxcli  |
| zwalletcli  | feature/notify-pr-zwalletcli  |
| 0chain  | feature/notify-pr  |
| blobber  | feature/notify-pr-blobber  |
| go-sdk  | NOT SUPPLIED  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| repo  | value |
| ------------- | ------------- |
| system-tests  | master  |
| zboxcli  | feature/notify-pr-zboxcli  |
| zwalletcli  | staging  |
| 0chain  | feature/notify-pr  |
| blobber  | feature/notify-pr-blobber  |
| go-sdk  | NOT OVERRIDDEN  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| repo  | value |
| ------------- | ------------- |
| system-tests  | master  |
| zboxcli  | feature/notify-pr-zboxcli  |
| zwalletcli  | staging  |
| 0chain  | feature/notify-pr  |
| blobber  | feature/notify-pr-blobber  |
| go-sdk  | NOT OVERRIDDEN  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| repo  | value |
| ------------- | ------------- |
| system-tests  | master  |
| zboxcli  | feature/notify-pr-zboxcli  |
| zwalletcli  | staging  |
| 0chain  | feature/notify-pr  |
| blobber  | feature/notify-pr-blobber  |
| gosdk  | NOT OVERRIDDEN  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| repo  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| 0boxcli  | feature/notify-pr-zboxcli  |
| 0walletcli  | staging  |
| 0chain  | feature/notify-pr  |
| blobber  | feature/notify-pr-blobber  |
| gosdk  | NOT OVERRIDDEN  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| zproxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/test-branch  |
| gosdk  | feature/notify-pr-gosdk  |
| 0boxcli  | feature/notify-pr-zboxcli  |
| 0walletcli  | feature/notify-pr-zwalletcli  |
| 0chain  | feature/notify-pr  |
| blobber  | feature/notify-pr-blobber  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| zproxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/test-branch  |
| gosdk  | feature/notify-pr-gosdk  |
| 0boxcli  | feature/notify-pr-zboxcli  |
| 0walletcli  | feature/notify-pr-zwalletcli  |
| 0chain  | feature/notify-pr  |
| blobber  | feature/notify-pr-blobber  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| zproxy  | staging  |
| 0search  | staging  |

**Review by cnlangzi — APPROVED** [review]
LGTM

**Pull request merged**
