### PR TITLE
should return 204 on empty blobbers list

### LINKED ISSUE #592: If there are no blobbers to honor requested allocation params, server returns wrong status code (500)
When the requested parameters can not be honored by any blobber, the backend response code is `500 - internal server error`. That is not a semantically correct error code.

The most appropriate code would be a 200 or 204 code with empty response, stating that the request was successfully made to a valid route, but there are no content.

### PR DESCRIPTION
**Pull request by dabasov**
## Fixes
when no blobbers can honor the allocation, 204 is returned

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

#goSdk https://github.com/0chain/gosdk/pull/475/files
zwalletcli https://github.com/0chain/zboxcli/pull/248

### CODE REVIEW

**Comment by peterlimg** [comment]
@dabasov please also check if gosdk need to be updated

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/204-on-empty-blobbers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | fix/204-on-empty-blobbers  |
| 0chain  | fix/204-on-empty-blobbers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — CHANGES_REQUESTED** [review]
Please adjust the unit tests about the 204 code.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | 204-on-empty-blobbers  |
| zwalletcli  | staging  |
| 0chain  | fix/204-on-empty-blobbers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/204-on-empty-blobbers  |
| zwalletcli  | staging  |
| 0chain  | fix/204-on-empty-blobbers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/204-on-empty-blobbers  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/204-on-empty-blobbers  |
| zwalletcli  | staging  |
| 0chain  | fix/204-on-empty-blobbers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request closed without merging**
