### PR TITLE
Update getblobbers endpoint

### LINKED ISSUE #1032: update getblobbers endpoint
from https://github.com/0chain/blobber/issues/127

[/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7/getblobbers](https://dev.0chain.net/miner01/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7/getblobbers) should be updated  in the storagesc code

- change `used` name to `allocated`
- add `used` for storage that is actually used by the client

### PR DESCRIPTION
**Pull request by realrisman**
## Changes
- Change `Used` name to `Allocated`

## Fixes
- Fix https://github.com/0chain/0chain/issues/1032

## Notes
- We need to update the SDK and others that use Blobber `Used` field

## Tests 
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by cnlangzi** [comment]
@realrisman do you forget to fixed 2nd item
- add used for storage that is actually used by the client

and could you fix it on gosdk/blobber too?

**Comment by realrisman** [comment]
> @realrisman do you forget to fixed 2nd item
> 
> * add used for storage that is actually used by the client
> 
> and could you fix it on gosdk/blobber too?

@cnlangzi for the 2nd item I thought it's already worked, when I add allocation the allocated/used value increase? please correct me if I'm wrong.

Ok I will update the gosdk/blobber too.

**Comment by realrisman** [comment]
@cnlangzi  I think I was wrong, so the 2nd item means I need to add the `Used` field for real storage used by the client?

I saw there is a field `TotalDataStored` on the Blobber struct, added 1 month ago by @Sriep but I don't see any logic/API using this field? is this field the same as the `Used` field?

cc: @guruhubb

**Comment by cnlangzi** [comment]
> @cnlangzi I think I was wrong, so the 2nd item means I need to add the `Used` field for real storage used by the client?
> 
> I saw there is a field `TotalDataStored` on the Blobber struct, added 1 month ago by @Sriep but I don't see any logic/API using this field? is this field the same as the `Used` field?
> 
> cc: @guruhubb

Yes. `Used` means real storage used by the client. so it should be updated if any file is uploaded/updated/deleted/copied...

it should be used on https://github.com/0chain/blobber/issues/127

**Comment by guruhubb** [comment]
Today we have these definitions that will be on the chain - see https://beta.0chain.net/blobber. @realrisman 
`Available` - how much storage capacity on the server reported by the blobber
`Staked` - how much has been staked by delegates
`Allocated` - space reserved by clients based on allocation contracts
`Used` - actual stored data by clients

So available > staked > allocated > used

Also `UnStaked` = available - staked so that delegates know which blobber is available for staking.
And `UnAllocated` = staked - allocated, so that clients know which blobber has room to store data.

**Comment by realrisman** [comment]
@guruhubb since this issue https://github.com/0chain/blobber/issues/127 is already covered by DevOps alerts, do we need to close this PR?

**Comment by peterlimg** [comment]
> 

@realrisman The https://github.com/0chain/blobber/issues/127 relies on the API response from this PR, so I don't think we need to close this PR. Also, please add the `used` to reflect the `Used - actual stored data by clients`.

**Comment by guruhubb** [comment]
@realrisman add Used and Available storage (when blobber registers, does bl-updates). 
Rename current available and used to Staked and Allocated respectively, as they are incorrect.

**Comment by cnlangzi** [comment]
@realrisman  I will take over this issue, please asks new issue from @dabasov , thanks.

**Comment by cnlangzi** [comment]
it will be fixed by https://github.com/0chain/0chain/pull/1370

**Pull request closed without merging**
