### PR TITLE
pagination improvements

### PR DESCRIPTION
**Pull request by dabasov**
refactored existent pagination
added to miner rest endpoints

### CODE REVIEW

**Review by peterlimg — CHANGES_REQUESTED** [review]
I suggest to move the pagination to the `smartcontract/rest` package since the `rest` package is for RESTful APIs. Also, it will help us avoid `common` package name conflicts when we using it

**Comment by dabasov** [comment]
> I suggest to move the pagination to the `smartcontract/rest` package since the `rest` package is for RESTful APIs. Also, it will help us avoid `common` package name conflicts when we using it

@peterlimg I've tried it at first, but it triggered cyclic dependencies error with more than 5 packages in the way

**Comment by peterlimg** [comment]
Ah, I see, perhaps we can do refactor later to have a better name to avoid naming conflicts. Any idea about the system test errors?

**Comment by dabasov** [comment]
> Ah, I see, perhaps we can do refactor later to have a better name to avoid naming conflicts. Any idea about the system test errors?

completely agree, don't like this `common2` packages either, I think we can remove common code to some other package or even repo and use it like common lib. 

restarted tests, looks like staging was not merged, I've already seen this tests failing and Kishan made hotfix for them

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | pagination  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/paggination-improved  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm, let's wait for the system test passing

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | pagination  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/paggination-improved  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
