### PR TITLE
Unit test for get blobbers from params

### LINKED ISSUE #2808: Add unit tests for GetBlobbersFromParams

### PR DESCRIPTION
**Pull request by tanishq67**
## Fixes

This PR is not yet complete, I have created it as a draft
-> I have written the unit test for get blobbers from params
The am testing if everything goes alright with 1st blobbers then I will create all the other blobbers accordingly.

## Changes
There are no changes apart from the blobbers_test file changes

## Need to be mentioned in CHANGELOG.md?
I don't think so.

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber: (*)
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by tanishq67** [comment]
@Jayashsatolia403 @dabasov please take a look.

**Comment by tanishq67** [comment]
@Jayashsatolia403 Please take a look at the values.

**Comment by tanishq67** [comment]
@Jayashsatolia403 @dabasov 
**When I am running the tests over my local system, the files "0chain.net/smartcontract/dbs/event" says "ok"** 

However, it's failing in here. What could be the reason? Please let me know how I can fix this.

image

**Review by Jayashsatolia403 — CHANGES_REQUESTED** [review]
Delete only the added blobbers. Also, use a cleanup function so that if it fails in the middle, it won't affect other tests.

**Comment by tanishq67** [comment]
> Delete only the added blobbers. Also, use a cleanup function so that if it fails in the middle, it won't affect other tests.

Hey @Jayashsatolia403, I have updated the PR. Please have a look at this. Is this what you meant?

image

**Comment by tanishq67** [comment]
@dabasov please take a look at the PR, I have added the **`cleanupBlobbers` function** because due to some unknown reason `defer clean` was not working properly as other unit tests were failing on GitHub

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by tanishq67** [comment]
@dabasov do I have to do anything?

**Pull request merged**
