### PR TITLE
New config validatorsPerChallenge

### LINKED ISSUE #1011: Set challenge's validator number from settings
Add a new setting  sc.yaml.storagesc.validators_per_challange.

In [addChallenge](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/challenge.go#L710) replace the number of validators from`alloc.DataShards` to the new setting `.validators_per_challange`.

We should also validate the partition size to be at least validators_per_challange.

### PR DESCRIPTION
**Pull request by avanaur**
## Changes

New SC config validators_per_challenge to be used as the number of validators when generating a challenge.

## Fixes
Fixes https://github.com/0chain/0chain/issues/1011

## Tests 
Tasks to complete before merging PR:
- [x]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by ma2b0043** [comment]
@avanaur when can we expect to close this PR?

**Comment by avanaur** [comment]
@ma2b0043 working on fixing the system test and hoping to close within next two days.

**Comment by avanaur** [comment]
NOTE: Above PR on actions repo must be merged first
https://github.com/0chain/actions/pull/28

**Review by dabasov — DISMISSED** [review]
lgtm

**Comment by avanaur** [comment]
@Sriep are you free to review this PR to make sure it is according to your expectation?

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
