### PR TITLE
Remove allocation name from storage smart contract.

### PR DESCRIPTION
**Pull request by areebusmani**
## Changes

Removes allocation name from storage smart contract.

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk: https://github.com/0chain/gosdk/pull/739
- system_test:
- zboxcli: https://github.com/0chain/zboxcli/pull/346
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | smart-contract-areeb  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — DISMISSED** [review]
Please also remove the `AllocationName` field from the event db.

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | areeb/allocname  |
| zwalletcli  | staging  |
| 0chain  | smart-contract-areeb  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | areeb/allocname  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | smart-contract-areeb  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | areeb/allocname  |
| zwalletcli  | staging  |
| 0chain  | smart-contract-areeb  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | areeb/allocname  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | smart-contract-areeb  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | areeb/allocname  |
| zwalletcli  | staging  |
| 0chain  | smart-contract-areeb  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | smart-contract-areeb  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | areeb/allocname  |
| zwalletcli  | staging  |
| 0chain  | smart-contract-areeb  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | areeb/allocname  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
