### PR TITLE
Remove stake pool offers

### LINKED ISSUE #577: StakePool, keep Offers in a seperate object - improve performance.
Split up the [stakePool](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L157) object, so the Offers are kept in a different object.

There are mainly treated independently so there is no reason to couple Offers with the Pools themselves. This has mainly been inspired by https://github.com/0chain/0chain/issues/568 where updateAllocationRequest is taking excessive time to update stake pool offers.

```go
type stakePool struct {
	Pools map[string]*delegatePool `json:"pools"`
	Offers map[string]*offerPool `json:"offers"`
	Rewards stakePoolRewards `json:"rewards"`.
	Settings stakePoolSettings `json:"settings"`
}
```

change to

```go
type stakePool struct {
	Pools map[string]*delegatePool `json:"pools"`
	Rewards stakePoolRewards `json:"rewards"`
	Settings stakePoolSettings `json:"settings"`
}

type stakePoolOffers{
	Offers map[string]*offerPool `json:"offers"`
        ... Aggragate Information ...
}
```
Investigate the possibility of keeping aggregate information in stakePoolOffers main object to remove the need to calculate it each time.

### PR DESCRIPTION
**Pull request by Sriep**
Tasks to complete before merging PR:
- [x]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [x]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR  
  
Associated PRs (Link as appropriate):
...

Previously we kept an array of offers in the stake pool, each referencing an allocation and expiry associated with a blobber. This is not scalable, so instead, we rely on summary statistics. 
1. Removes the offers array from `stakePool`
2. Add  `TotalOffers` and `TotalUnStake` state.Balance fields to replace the offers array.
3. Update TotalOffers and TotalUnstake as necessary when total stake and total to unstake changes.
4. Remove all references to interest payments.

Related PRs https://github.com/0chain/system_test/pull/162 https://github.com/0chain/gosdk/pull/355 and https://github.com/0chain/zboxcli/pull/155 and https://github.com/0chain/gosdk/pull/355.

### CODE REVIEW

**Comment by Sriep** [comment]
Green test run https://github.com/0chain/system_test/actions/runs/1745374265

**Comment by Sriep** [comment]
Second green system test https://github.com/0chain/system_test/actions/runs/1746786632

**Review by dabasov — DISMISSED** [review]
lgtm

**Review by ssardana96 — DISMISSED** [review]

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | sp-changes  |
| zwalletcli  | staging  |
| 0chain  | sp_offers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | stake_pool_update  |
| gosdk  | sp-changes  |
| zboxcli  | sp-changes  |
| zwalletcli  | staging  |
| 0chain  | sp_offers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | stake_pool_update  |
| gosdk  | sp-changes  |
| zboxcli  | sp-changes  |
| zwalletcli  | staging  |
| 0chain  | sp_offers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | stake_pool_update  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | sp-changes  |
| zwalletcli  | staging  |
| 0chain  | sp_offers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | stake_pool_update  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | sp_offers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — DISMISSED** [review]
lgtm

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
