### PR TITLE
Remove interest pool

### LINKED ISSUE #1215: Remove interestpoolsc
We need to remove interestpoolsc and all gosdk/zwalletcli related commands.

### PR DESCRIPTION
**Pull request by Sriep**
## Changes
Remove all code related to interest pool smartcontract
## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk: https://github.com/0chain/gosdk/pull/471
- system_test: https://github.com/0chain/system_test/pull/286
- zboxcli:
- zwalletcli: https://github.com/0chain/zwalletcli/pull/135
- 0chain: https://github.com/0chain/0chain/pull/1329
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove_interest_pool  |
| gosdk  | remove_interest_pool  |
| zboxcli  | staging  |
| zwalletcli  | remove_interest_pool  |
| 0chain  | remove_interest_pool  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove_interest_pool  |
| gosdk  | remove_interest_pool  |
| zboxcli  | staging  |
| zwalletcli  | remove_interest_pool  |
| 0chain  | remove_interest_pool  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Review by peterlimg — APPROVED** [review]
lgtm

**Pull request merged**
