### PR TITLE
Fix getUsersPool endpoint

### LINKED ISSUE #1381: Bug on `/getUserPools` endpoint
This endpoint was to return pools of miners or sharders of given client id, however, since the `speum.Miner` value is 0, which means when we try to get miner's user delegate pools with the code below, the filter would never be applied as it is the default value when the DeletePool struct is pass to the `Where()` clause. So the `ProviderType` does not work actually, therefore we will return all the items of the `userId`.

https://github.com/0chain/0chain/blob/fdb05140743c7a450b6025ce462b557dec5bd6c0/code/go/0chain.net/smartcontract/dbs/event/delegate_pool.go#L97-L107

Also, the response will be more readable if group the pools with different provider names as doc shows in zwalletcli.

image

### PR DESCRIPTION
**Pull request by peterlimg**
## Fixes
- closes #1381 

## Changes

Start Provider enum value from 1

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber: https://github.com/0chain/blobber/pull/733
- gosdk: https://github.com/0chain/gosdk/pull/496
- system_test: https://github.com/0chain/system_test/pull/308
- zboxcli: https://github.com/0chain/zboxcli/pull/268
- zwalletcli: https://github.com/0chain/zwalletcli/pull/149

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/getUsersPool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/getUsersPool  |
| zwalletcli  | fix/getUsersPool  |
| 0chain  | fix/getUserPools  |
| blobber  | fix/getUsersPool  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/getUsersPool  |
| gosdk  | fix/getUsersPool  |
| zboxcli  | fix/getUsersPool  |
| zwalletcli  | fix/getUsersPool  |
| 0chain  | fix/getUserPools  |
| blobber  | fix/getUsersPool  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/getUsersPool  |
| gosdk  | fix/getUsersPool  |
| zboxcli  | fix/getUsersPool  |
| zwalletcli  | fix/getUsersPool  |
| 0chain  | fix/getUserPools  |
| blobber  | fix/getUsersPool  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/getUsersPool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/getUsersPool  |
| zwalletcli  | fix/getUsersPool  |
| 0chain  | fix/getUserPools  |
| blobber  | fix/getUsersPool  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by cnlangzi — APPROVED** [review]

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | fix/getUsersPool  |
| 0chain  | fix/getUserPools  |
| blobber  | fix/getUsersPool  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
